# K3 students
k3_students = [
"Aadhini Kannappan",
"Adithya Senthilnathan",
"Akanksha Galagali",
"Aniruddha Paik",
"Ankita Sahoo",
"Anoushka Rai",
"Arabinda Sahoo",
"Ashpriha Biswas",
"Ashwini",
"Asmita Das",
"Aurobrata Panda",
"Bhaswar Ghosh",
"Dyuman Aditya (A.G.)",
"Harshini Nilakantan",
"Jenish Halvadia",
"Jeyasuriya Gopinath",
"Kruti Shah",
"Raja Banerjee",
"Sarthak Bhattacharya",
"Selvamira (D)",
"Shivani (M)",
"Subhasini Mohanty",
"Suchitra Rani Sahu",
"Suvin Varma",
"Swapna Sahoo",
"Surajit Acharya",
"Tenzing N Rigdrol",
"Tenzing N Rigzang",
"Uttama (T)",
"Vankayala Amit"
]

# K2 students
k2_students = [
"Aaryan Ananda",
"Abeni Manzar",
"Aditi Mandali",
"Aditi Sharma",
"Aditya Kumar Mahapatra",
"Ahana Ghosh",
"Aniket Deb",
"Anushka Mitra",
"Aurokrishna (S)",
"Devdatta Chatterjee",
"Harshita Nilakantan",
"Janaki Pande",
"Kirttiparnna Swain",
"Kush Patel",
"Markendeya Achille Morsiani",
"Meera Joshi",
"Narendran (K)",
"Praketa Kumar Behera",
"Ramyak Samantaray",
"Ritam Lenka",
"Sayuri Mima",
"Sephali Priyadarshini Nay",
"Shubha Sanket Samantaray",
"Smruti Ranjan Sahoo",
"Sreevidhya",
"Sumitaa Ghosal",
"Svaha Myvannan",
"Swarnojit Bhattacharjee",
"Vibhu Dalal"
]

# K1 students
k1_students = [
"Aditya Patra",
"Aishi Dey",
"Ananyaa Baskar",
"Arijit Podder",
"Arundhati Panda",
"Asmi Dolia",
"Auro Adarsh",
"Baivab Dutta",
"Chaitanya Sharma",
"Daffodil Mazumdar",
"Divyanshu Pradhan",
"Kaninika Majumdar",
"Lakshman Baliyarsingh",
"Jishnu (P.S.)",
"Naman R Singh",
"Pratyush Jena",
"Rayih Chatterjee",
"Rishabh Mukund",
"Ritam Mondal",
"Sai Roshini Miriyala",
"Samarpan Jena",
"Saurabh Ranjan Das",
"Shashwati Dey",
"Shinjini Roy",
"Skandhan Karthikeyan",
"Smita Chaturvedy",
"Souryashree Samarpan",
"Sumit Singh",
"Sunanda Sahoo",
"Urva Chandrani",
"Vaiditi Vipul Acharya",
"Vivek-Alex Sharan"
]